// generated by worker/src/abi/sync.ts from contracts/out — do not edit
export const LEDGER_ABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "admin",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "engine",
        "type": "address",
        "internalType": "contract ScoreEngine"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "DEFAULT_ADMIN_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "NATIVE_RECORDER_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "RECORDER_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SOURCE_CHAIN_KEY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "currentSourceBlock",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "factCount",
    "inputs": [
      {
        "name": "subject",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "factIds",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "facts",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "subject",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "factType",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amountRaw",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountUsd6",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "sourceBlock",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "queryId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "recordedAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getBreakdown",
    "inputs": [
      {
        "name": "subject",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct ScoreEngine.Breakdown",
        "components": [
          {
            "name": "base",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "repayPts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "volumePts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "ratioPts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "tenurePts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "recencyPts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "nativePts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liquidationPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "defaultPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "score",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "tier",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getFacts",
    "inputs": [
      {
        "name": "subject",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "internalType": "struct Fact[]",
        "components": [
          {
            "name": "subject",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "factType",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "reserve",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "amountRaw",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amountUsd6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "sourceBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "queryId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "recordedAt",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getProfile",
    "inputs": [
      {
        "name": "subject",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct CreditProfile",
        "components": [
          {
            "name": "borrowCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "repayCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "liquidationCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "borrowedVolumeUsd6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "repaidVolumeUsd6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "firstActivityBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastRepayBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastLiquidationBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nativeRepayCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "nativeDefaultCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRoleAdmin",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getScore",
    "inputs": [
      {
        "name": "subject",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "score",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "tier",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "grantRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "hasRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latestSourceBlock",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "profiles",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "borrowCount",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "repayCount",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "liquidationCount",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "borrowedVolumeUsd6",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "repaidVolumeUsd6",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "firstActivityBlock",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "lastRepayBlock",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "lastLiquidationBlock",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "nativeRepayCount",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "nativeDefaultCount",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "updatedAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "queryFactCount",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "recordFact",
    "inputs": [
      {
        "name": "subject",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "factType",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amountRaw",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountUsd6",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "sourceBlock",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "queryId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "factId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "recordNativeDefault",
    "inputs": [
      {
        "name": "subject",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "recordNativeRepay",
    "inputs": [
      {
        "name": "subject",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "callerConfirmation",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "scoreEngine",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ScoreEngine"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setScoreEngine",
    "inputs": [
      {
        "name": "engine",
        "type": "address",
        "internalType": "contract ScoreEngine"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "totalFacts",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "totalSubjects",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "FactStored",
    "inputs": [
      {
        "name": "factId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "subject",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "factType",
        "type": "uint8",
        "indexed": true,
        "internalType": "uint8"
      },
      {
        "name": "queryId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "sourceBlock",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProfileUpdated",
    "inputs": [
      {
        "name": "subject",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "score",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "tier",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleAdminChanged",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previousAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleGranted",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleRevoked",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ScoreEngineUpdated",
    "inputs": [
      {
        "name": "engine",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AccessControlBadConfirmation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AccessControlUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "neededRole",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  }
] as const;
