// generated by worker/src/abi/sync.ts from contracts/out — do not edit
export const SCORE_ENGINE_ABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "TIER_BRONZE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TIER_GOLD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TIER_PLATINUM",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TIER_SILVER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "breakdown",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct CreditProfile",
        "components": [
          {
            "name": "borrowCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "repayCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "liquidationCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "borrowedVolumeUsd6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "repaidVolumeUsd6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "firstActivityBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastRepayBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastLiquidationBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nativeRepayCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "nativeDefaultCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "nowBlock",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "b",
        "type": "tuple",
        "internalType": "struct ScoreEngine.Breakdown",
        "components": [
          {
            "name": "base",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "repayPts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "volumePts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "ratioPts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "tenurePts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "recencyPts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "nativePts",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liquidationPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "defaultPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "score",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "tier",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "defaultParams",
    "inputs": [],
    "outputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct ScoreEngine.Params",
        "components": [
          {
            "name": "base",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "repayPtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "repayCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "volumePtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "volumeCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "ratioMax",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "tenureUnitBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "tenureCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "tenurePtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "recencyFullBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "recencyHalfBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "recencyFullPts",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "recencyHalfPts",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "nativePtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "nativeCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "liqFirstPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liqExtraPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liqRecentPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liqRecentBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "defaultPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "silverMin",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "goldMin",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "platinumMin",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "params",
    "inputs": [],
    "outputs": [
      {
        "name": "base",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "repayPtsEach",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "repayCap",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "volumePtsEach",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "volumeCap",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "ratioMax",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "tenureUnitBlocks",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "tenureCap",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "tenurePtsEach",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "recencyFullBlocks",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "recencyHalfBlocks",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "recencyFullPts",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "recencyHalfPts",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "nativePtsEach",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "nativeCap",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "liqFirstPenalty",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "liqExtraPenalty",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "liqRecentPenalty",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "liqRecentBlocks",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "defaultPenalty",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "minScore",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "maxScore",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "silverMin",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "goldMin",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "platinumMin",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "score",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct CreditProfile",
        "components": [
          {
            "name": "borrowCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "repayCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "liquidationCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "borrowedVolumeUsd6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "repaidVolumeUsd6",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "firstActivityBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastRepayBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastLiquidationBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nativeRepayCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "nativeDefaultCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "nowBlock",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setParams",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct ScoreEngine.Params",
        "components": [
          {
            "name": "base",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "repayPtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "repayCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "volumePtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "volumeCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "ratioMax",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "tenureUnitBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "tenureCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "tenurePtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "recencyFullBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "recencyHalfBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "recencyFullPts",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "recencyHalfPts",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "nativePtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "nativeCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "liqFirstPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liqExtraPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liqRecentPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liqRecentBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "defaultPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "silverMin",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "goldMin",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "platinumMin",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "tierOf",
    "inputs": [
      {
        "name": "s",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ParamsUpdated",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct ScoreEngine.Params",
        "components": [
          {
            "name": "base",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "repayPtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "repayCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "volumePtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "volumeCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "ratioMax",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "tenureUnitBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "tenureCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "tenurePtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "recencyFullBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "recencyHalfBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "recencyFullPts",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "recencyHalfPts",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "nativePtsEach",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "nativeCap",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "liqFirstPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liqExtraPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liqRecentPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liqRecentBlocks",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "defaultPenalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxScore",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "silverMin",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "goldMin",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "platinumMin",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const;
