// Copies the ABIs the worker and web need out of the Foundry build into TypeScript modules.
import fs from 'node:fs';
import path from 'node:path';
import { REPO_ROOT } from '../config.js';

const out = path.join(REPO_ROOT, 'contracts', 'out');
const targets: Array<[string, string, string]> = [
  ['CreditBureauASC.sol/CreditBureauASC.json', 'bureau.ts', 'BUREAU_ABI'],
  ['CreditLedger.sol/CreditLedger.json', 'ledger.ts', 'LEDGER_ABI'],
  ['CreditPassport.sol/CreditPassport.json', 'passport.ts', 'PASSPORT_ABI'],
  ['TieredLender.sol/TieredLender.json', 'lender.ts', 'LENDER_ABI'],
  ['TestUSD.sol/TestUSD.json', 'tusd.ts', 'TUSD_ABI'],
  ['ScoreEngine.sol/ScoreEngine.json', 'scoreEngine.ts', 'SCORE_ENGINE_ABI'],
];
for (const [src, dst, name] of targets) {
  const art = JSON.parse(fs.readFileSync(path.join(out, src), 'utf8'));
  const body = `// generated by worker/src/abi/sync.ts from contracts/out — do not edit\nexport const ${name} = ${JSON.stringify(art.abi, null, 2)} as const;\n`;
  fs.writeFileSync(path.join(REPO_ROOT, 'worker', 'src', 'abi', dst), body);
  const webDir = path.join(REPO_ROOT, 'web', 'src', 'abi');
  if (fs.existsSync(webDir)) fs.writeFileSync(path.join(webDir, dst), body);
  console.log('wrote', dst);
}
